-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 18:37:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FH` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema HST
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HST` ;
USE `FH` ;

-- -----------------------------------------------------
-- Table `FH`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Paterno` VARCHAR(50) NULL,
  `Materno` VARCHAR(50) NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Lugar_Nacimiento` VARCHAR(20) NULL,
  `Sexo` VARCHAR(2) NULL,
  `CURP` VARCHAR(20) NOT NULL,
  `RFC` VARCHAR(15) NULL,
  `Telefono` VARCHAR(10) NULL,
  `Email` VARCHAR(50) NULL,
  `Estado_Civil` VARCHAR(20) NULL,
  `No_Control` VARCHAR(8) NULL,
  `No_Seguro` VARCHAR(20) NULL,
  `Tipo_Nomina` VARCHAR(20) NULL,
  `Tipo_Empleo` VARCHAR(15) NULL,
  `Foto` TEXT NULL,
  `Estatus` VARCHAR(15) NULL,
  PRIMARY KEY (`CURP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Personales` (
  `PersonalesID` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Tipo_Sangre` VARCHAR(5) NULL,
  `Discapacidad` BINARY(1) NULL,
  `Tipo_Discapacidad` VARCHAR(45) NULL,
  `Madre` VARCHAR(150) NULL,
  `Padre` VARCHAR(150) NULL,
  `Licencia_Conducir` VARCHAR(15) NULL,
  `Licencia_vigencia` DATE NULL,
  `Licencia_Lugar_Expedicion` VARCHAR(25) NULL,
  `Pension_Alimenticia` BINARY(1) NULL,
  PRIMARY KEY (`PersonalesID`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Biometrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Biometrico` (
  `idBiometrico` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Huella` TEXT NULL,
  PRIMARY KEY (`idBiometrico`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Domicilio` (
  `idDomicilio` INT NOT NULL,
  `Calle` VARCHAR(50) NULL,
  `No_Exterior` INT(11) NULL,
  `No_Interior` VARCHAR(15) NULL,
  `CP` INT(6) NULL,
  `Colonia` VARCHAR(100) NULL,
  `Ciudad_Municipio` VARCHAR(100) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idDomicilio`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Escolaridad` (
  `idEscolaridad` INT NOT NULL,
  `Escolaridad` VARCHAR(20) NULL,
  `Fecha_Documento` DATE NULL,
  `Documento_Obtenido` VARCHAR(45) NULL,
  `Institucion` VARCHAR(50) NULL,
  `Area` VARCHAR(50) NULL,
  `Curp` VARCHAR(20) NULL,
  PRIMARY KEY (`idEscolaridad`),
  INDEX `CURP_idx` (`Curp` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`Curp`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Area` (
  `idArea` INT NOT NULL,
  `Unidad_Administrativa` VARCHAR(120) NULL,
  `Direccion_Funcional` VARCHAR(120) NULL,
  `Subdirecccion_Funcional` VARCHAR(120) NULL,
  `Area_Funcional` VARCHAR(120) NULL,
  `Secretaria` VARCHAR(120) NULL,
  `Direccion` VARCHAR(120) NULL,
  `Horario_Entrada` VARCHAR(10) NULL,
  `Horario_Salida` VARCHAR(10) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idArea`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Salario` (
  `idSalario` INT NOT NULL,
  `Bruto` DECIMAL(8,2) NULL,
  `Neto` DECIMAL(8,2) NULL,
  `Canasta_Basica` DECIMAL(8,2) NULL,
  `Cup_Bruto` DECIMAL(8,2) NULL,
  `Cup_Neto` DECIMAL(8,2) NULL,
  `Total_Bruto` DECIMAL(8,2) NULL,
  `Total_Neto(8,2)` DECIMAL(8,2) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idSalario`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Movimiento` (
  `idMovimiento` INT NOT NULL,
  `Tipo` VARCHAR(15) NULL,
  `Departamento` VARCHAR(120) NULL,
  `Puesto` VARCHAR(75) NULL,
  `Fecha` DATE NULL,
  `Causa` TEXT NULL,
  `Observaciones` TEXT NULL,
  `Otros` TEXT NULL,
  `Depto_Actual` VARCHAR(150) NULL,
  `Puesto_Actual` VARCHAR(150) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idMovimiento`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Hijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Hijos` (
  `idHijos` INT NOT NULL,
  `Nombre` VARCHAR(150) NULL,
  `Edad` INT(11) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idHijos`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `FH`.`Contacto_Emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Contacto_Emergencia` (
  `idContacto_Emergencia` INT NOT NULL,
  `Nombre` VARCHAR(150) NULL,
  `Parentesco` VARCHAR(20) NULL,
  `Telefono` INT(10) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idContacto_Emergencia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Pension_Alimenticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Pension_Alimenticia` (
  `idPension_Alimenticia` INT NOT NULL,
  `Fecha_InicioPA` DATE NULL,
  `Fecha_FinPA` DATE NULL,
  `Nombre_HijoPA` VARCHAR(150) NULL,
  `Acta_Matrimonio` VARCHAR(15) NULL,
  `Acta_Hijo` VARCHAR(15) NULL,
  `Constancia_Estudios_Hijo` VARCHAR(30) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idPension_Alimenticia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Placa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Placa` (
  `idPlaca` INT NOT NULL,
  `No_Placa` VARCHAR(30) NULL,
  `CUIP` VARCHAR(30) NULL,
  `No_CUIP` VARCHAR(30) NULL,
  `Situacion_CUIP` VARCHAR(30) NULL,
  `Fecha_Em_CUP` DATE NULL,
  `CUP` BINARY NULL,
  `No_CUP` VARCHAR(30) NULL,
  PRIMARY KEY (`idPlaca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Contratacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Contratacion` (
  `idContratacion` INT NOT NULL,
  `Tipo_Contrato` VARCHAR(75) NULL,
  `Categoria` VARCHAR(120) NULL,
  `Plaza` INT(11) NULL,
  `Funcion` VARCHAR(120) NULL,
  `Vector_Region` VARCHAR(15) NULL,
  `Placa` INT(11) NULL,
  `Observacion_Academia` TEXT NULL,
  `Observacion_Juridico` TEXT NULL,
  `Salario` INT(11) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idContratacion`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  INDEX `Placa_idx` (`Placa` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Placa`
    FOREIGN KEY (`Placa`)
    REFERENCES `FH`.`Placa` (`idPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Formacion_Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Formacion_Academia` (
  `idFormacion_Academia` INT NOT NULL,
  `Descripcion` TEXT NULL,
  `Tipo_Formacion` VARCHAR(30) NULL,
  `Fecha_InicioFA` DATE NULL,
  `Fecha_Termino` DATE NULL,
  `Horas_Curso` VARCHAR(15) NULL,
  `Institucion` VARCHAR(30) NULL,
  `Evaluacion_CBP` VARCHAR(15) NULL,
  `Fecha_CBP` DATE NULL,
  `Evaluacion_Desempeño` VARCHAR(15) NULL,
  `Fecha_Edd` DATE NULL,
  `Fecha_Ecc` DATE NULL,
  `Resultados_Ecc` VARCHAR(15) NULL,
  `Vigencia_Ecc` VARCHAR(15) NULL,
  `Fecha_Vigencia` DATE NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idFormacion_Academia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Incapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Incapacidad` (
  `idIncapacidad` INT NOT NULL,
  `Tipo_Incapacidad` VARCHAR(50) NULL,
  `Descripcion` TEXT NULL,
  `Trayecto` BINARY NULL,
  `Servicio` BINARY NULL,
  `Fecha_Entrega` DATE NULL,
  `Fecha_Llenado` DATE NULL,
  `Fecha_Calificado` DATE NULL,
  `Fecha_Recaida` DATE NULL,
  `Fecha_Alta` DATE NULL,
  `Fecha_Inicio_Incapacidad` DATE NULL,
  `Fecha_Fin_Incapacidad` DATE NULL,
  `Dias` INT NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idIncapacidad`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Fatiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Fatiga` (
  `idFatiga` INT NOT NULL,
  `Nombre_Elemento` VARCHAR(150) NULL,
  `Fecha_Asistencia` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idFatiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Sanciones` (
  `idSanciones` INT NOT NULL,
  `Tipo_Sancion` VARCHAR(75) NULL,
  `Folio_Oficio_Sancion` VARCHAR(30) NULL,
  `Fecha_Efecto` DATE NULL,
  `Fecha_Reincorporacion` DATE NULL,
  `Asunto` TEXT NULL,
  `Tipo` VARCHAR(10) NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idSanciones`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `Tipo_Permiso` VARCHAR(15) NULL,
  `Fecha_InicioPermiso` DATE NULL,
  `Fecha_FinPermiso` DATE NULL,
  `Observaciones` TEXT NULL,
  `CURP` VARCHAR(20) NULL,
  PRIMARY KEY (`idPermisos`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Vacaciones` (
  `idVacaciones` INT NOT NULL,
  `Fecha_InicioVacaciones` DATE NULL,
  `Fecha_FinVacaciones` DATE NULL,
  `Tipo` TEXT NULL,
  `IdPermiso` INT NULL,
  PRIMARY KEY (`idVacaciones`),
  INDEX `Permiso_idx` (`IdPermiso` ASC) VISIBLE,
  CONSTRAINT `Permiso`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `FH`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Licencia` (
  `idLicencia` INT NOT NULL,
  `Fecha_InicioLicencia` DATE NULL,
  `Fecha_FinLicencia` DATE NULL,
  `ObservacionesLicencia` TEXT NULL,
  `IdPermiso` INT NULL,
  PRIMARY KEY (`idLicencia`),
  INDEX `Permiso_idx` (`IdPermiso` ASC) VISIBLE,
  CONSTRAINT `Permiso`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `FH`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Diagnostico_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Diagnostico_Medico` (
  `idDiagnostico_Medico` INT NOT NULL,
  `Diagnostico` TEXT NULL,
  `Folio_Serie` VARCHAR(30) NULL,
  `Clinica` VARCHAR(50) NULL,
  `Medico` VARCHAR(150) NULL,
  `Cedula` VARCHAR(30) NULL,
  `IdIncapacidad` INT NULL,
  PRIMARY KEY (`idDiagnostico_Medico`),
  INDEX `Incapacidad_idx` (`IdIncapacidad` ASC) VISIBLE,
  CONSTRAINT `Incapacidad`
    FOREIGN KEY (`IdIncapacidad`)
    REFERENCES `FH`.`Incapacidad` (`idIncapacidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`CAT_Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`CAT_Estados` (
  `idCAT_Estados` INT NOT NULL,
  `Estado` VARCHAR(25) NULL,
  `Abreviacion` VARCHAR(7) NULL,
  PRIMARY KEY (`idCAT_Estados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`CAT_Tipo_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`CAT_Tipo_Empleado` (
  `idCAT_Tipo_Empleado` INT NOT NULL,
  `Tipo` VARCHAR(12) NULL,
  `Abreviacion` VARCHAR(5) NULL,
  PRIMARY KEY (`idCAT_Tipo_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`CAT_Categoria_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`CAT_Categoria_Empleado` (
  `idCAT_Categoria_Empleado` INT NOT NULL,
  `Categoria` VARCHAR(20) NULL,
  `Descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`idCAT_Categoria_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`CAT_Estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`CAT_Estatus` (
  `idCAT_Estatus` INT NOT NULL,
  `Estatus` VARCHAR(15) NULL,
  `Abreviacion` VARCHAR(5) NULL,
  PRIMARY KEY (`idCAT_Estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `PaternoU` VARCHAR(20) NULL,
  `MaternoU` VARCHAR(20) NULL,
  `No_ControlU` VARCHAR(10) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Area` VARCHAR(15) NULL,
  `Tipo_Cuenta` VARCHAR(15) NULL,
  `Contraseña` VARCHAR(10) NULL,
  `Estatus` BINARY NULL,
  `Fecha_Registro` DATE NULL,
  `Fecha_Actualizacion` DATE NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Seguro_Vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Seguro_Vida` (
  `idSeguro_Vida` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Poliza` VARCHAR(13) NULL,
  PRIMARY KEY (`idSeguro_Vida`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FH`.`Beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FH`.`Beneficiarios` (
  `idBeneficiarios` INT NOT NULL,
  `Nombre_Beneficiario` VARCHAR(150) NULL,
  `Parentesco` VARCHAR(20) NULL,
  `Porcentaje` INT(11) NULL,
  `idSeguro_Vida` INT NULL,
  PRIMARY KEY (`idBeneficiarios`),
  INDEX `IdSeguro_Vida_idx` (`idSeguro_Vida` ASC) VISIBLE,
  CONSTRAINT `IdSeguro_Vida`
    FOREIGN KEY (`idSeguro_Vida`)
    REFERENCES `FH`.`Seguro_Vida` (`idSeguro_Vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `HST` ;

-- -----------------------------------------------------
-- Table `HST`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Empleado` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Paterno` VARCHAR(50) NULL,
  `Materno` VARCHAR(50) NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Lugar_Nacimiento` VARCHAR(20) NULL,
  `Sexo` VARCHAR(2) NULL,
  `CURP` VARCHAR(20) NOT NULL,
  `RFC` VARCHAR(15) NULL,
  `Telefono` VARCHAR(10) NULL,
  `Email` VARCHAR(50) NULL,
  `Estado_Civil` VARCHAR(20) NULL,
  `No_Control` VARCHAR(8) NULL,
  `No_Seguro` VARCHAR(20) NULL,
  `Tipo_Nomina` VARCHAR(20) NULL,
  `Tipo_Empleo` VARCHAR(15) NULL,
  `Foto` VARCHAR(30) NULL,
  `Estatus` VARCHAR(15) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_Mod` VARCHAR(10) NULL,
  `Fecha_ModE` DATE NULL,
  PRIMARY KEY (`CURP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Area` (
  `idArea` INT NOT NULL,
  `Unidad_Administrativa` VARCHAR(120) NULL,
  `Direccion_Funcional` VARCHAR(120) NULL,
  `Subdirecccion_Funcional` VARCHAR(120) NULL,
  `Area_Funcional` VARCHAR(120) NULL,
  `Secretaria` VARCHAR(120) NULL,
  `Direccion` VARCHAR(120) NULL,
  `Horario_Entrada` VARCHAR(10) NULL,
  `Horario_Salida` VARCHAR(10) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_Mod` VARCHAR(10) NULL,
  `Fecha_ModA` DATE NULL,
  PRIMARY KEY (`idArea`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Biometrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Biometrico` (
  `idBiometrico` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Huella` TEXT NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModBi` VARCHAR(10) NULL,
  `Fecha_ModBi` DATE NULL,
  PRIMARY KEY (`idBiometrico`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`CAT_Categoria_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`CAT_Categoria_Empleado` (
  `idCAT_Categoria_Empleado` INT NOT NULL,
  `Categoria` VARCHAR(20) NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModCEm` VARCHAR(10) NULL,
  `Fecha_ModCEm` DATE NULL,
  PRIMARY KEY (`idCAT_Categoria_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`CAT_Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`CAT_Estados` (
  `idCAT_Estados` INT NOT NULL,
  `Estado` VARCHAR(25) NULL,
  `Abreviacion` VARCHAR(7) NULL,
  PRIMARY KEY (`idCAT_Estados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`CAT_Estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`CAT_Estatus` (
  `idCAT_Estatus` INT NOT NULL,
  `Estatus` VARCHAR(15) NULL,
  `Abreviacion` VARCHAR(5) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModEus` VARCHAR(10) NULL,
  `Fecha_ModEus` DATE NULL,
  PRIMARY KEY (`idCAT_Estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`CAT_Tipo_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`CAT_Tipo_Empleado` (
  `idCAT_Tipo_Empleado` INT NOT NULL,
  `Tipo` VARCHAR(12) NULL,
  `Abreviacion` VARCHAR(5) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModTE` VARCHAR(10) NULL,
  `Fecha_ModTE` DATE NULL,
  PRIMARY KEY (`idCAT_Tipo_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Contacto_Emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Contacto_Emergencia` (
  `idContacto_Emergencia` INT NOT NULL,
  `Nombre` VARCHAR(150) NULL,
  `Parentesco` VARCHAR(20) NULL,
  `Telefono` INT(10) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModCE` VARCHAR(10) NULL,
  `Fecha_ModCE` DATE NULL,
  PRIMARY KEY (`idContacto_Emergencia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Contratacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Contratacion` (
  `idContratacion` INT NOT NULL,
  `Tipo_Contrato` VARCHAR(75) NULL,
  `Categoria` VARCHAR(120) NULL,
  `Plaza` INT(11) NULL,
  `Funcion` VARCHAR(120) NULL,
  `Vector_Region` VARCHAR(15) NULL,
  `Placa` INT(11) NULL,
  `Observacion_Academia` TEXT NULL,
  `Observacion_Juridico` TEXT NULL,
  `Salario` INT(11) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModC` VARCHAR(10) NULL,
  `Feha_ModC` DATE NULL,
  PRIMARY KEY (`idContratacion`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  INDEX `Placa_idx` (`Placa` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Placa`
    FOREIGN KEY (`Placa`)
    REFERENCES `FH`.`Placa` (`idPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Diagnostico_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Diagnostico_Medico` (
  `idDiagnostico_Medico` INT NOT NULL,
  `Diagnostico` TEXT NULL,
  `Folio_Serie` VARCHAR(30) NULL,
  `Clinica` VARCHAR(50) NULL,
  `Medico` VARCHAR(150) NULL,
  `Cedula` VARCHAR(30) NULL,
  `IdIncapacidad` INT NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModDM` VARCHAR(10) NULL,
  `Fecha_ModDM` DATE NULL,
  PRIMARY KEY (`idDiagnostico_Medico`),
  INDEX `Incapacidad_idx` (`IdIncapacidad` ASC) VISIBLE,
  CONSTRAINT `Incapacidad`
    FOREIGN KEY (`IdIncapacidad`)
    REFERENCES `FH`.`Incapacidad` (`idIncapacidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Domicilio` (
  `idDomicilio` INT NOT NULL,
  `Calle` VARCHAR(50) NULL,
  `No_Exterior` INT(11) NULL,
  `No_Interior` VARCHAR(15) NULL,
  `CP` INT(6) NULL,
  `Colonia` VARCHAR(100) NULL,
  `Ciudad_Municipio` VARCHAR(100) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModD` VARCHAR(10) NULL,
  `Fecha_ModD` DATE NULL,
  PRIMARY KEY (`idDomicilio`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Escolaridad` (
  `idEscolaridad` INT NOT NULL,
  `Escolaridad` VARCHAR(20) NULL,
  `Fecha_Documento` DATE NULL,
  `Documento_Obtenido` VARCHAR(45) NULL,
  `Institucion` VARCHAR(50) NULL,
  `Area` VARCHAR(50) NULL,
  `Curp` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModEs` VARCHAR(10) NULL,
  `Fecha_ModEs` DATE NULL,
  PRIMARY KEY (`idEscolaridad`),
  INDEX `CURP_idx` (`Curp` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`Curp`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Fatiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Fatiga` (
  `idFatiga` INT NOT NULL,
  `Nombre_Elemento` VARCHAR(150) NULL,
  `Fecha_Asistencia` DATE NULL,
  `Hora` TIME NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModF` VARCHAR(10) NULL,
  `Fecha_ModF` DATE NULL,
  PRIMARY KEY (`idFatiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Formacion_Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Formacion_Academia` (
  `idFormacion_Academia` INT NOT NULL,
  `Descripcion` TEXT NULL,
  `Tipo_Formacion` VARCHAR(30) NULL,
  `Fecha_InicioFA` DATE NULL,
  `Fecha_Termino` DATE NULL,
  `Horas_Curso` VARCHAR(15) NULL,
  `Institucion` VARCHAR(30) NULL,
  `Evaluacion_CBP` VARCHAR(15) NULL,
  `Fecha_CBP` DATE NULL,
  `Evaluacion_Desempeño` VARCHAR(15) NULL,
  `Fecha_Edd` DATE NULL,
  `Fecha_Ecc` DATE NULL,
  `Resultados_Ecc` VARCHAR(15) NULL,
  `Vigencia_Ecc` VARCHAR(15) NULL,
  `Fecha_Vigencia` DATE NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModFA` VARCHAR(10) NULL,
  `Fecha_ModFA` DATE NULL,
  PRIMARY KEY (`idFormacion_Academia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Hijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Hijos` (
  `idHijos` INT NOT NULL,
  `Nombre` VARCHAR(150) NULL,
  `Edad` INT(11) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModH` VARCHAR(10) NULL,
  `Fecha_ModH` DATE NULL,
  PRIMARY KEY (`idHijos`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `HST`.`Incapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Incapacidad` (
  `idIncapacidad` INT NOT NULL,
  `Tipo_Incapacidad` VARCHAR(50) NULL,
  `Descripcion` TEXT NULL,
  `Trayecto` BINARY NULL,
  `Servicio` BINARY NULL,
  `Fecha_Entrega` DATE NULL,
  `Fecha_Llenado` DATE NULL,
  `Fecha_Calificado` DATE NULL,
  `Fecha_Recaida` DATE NULL,
  `Fecha_Alta` DATE NULL,
  `Fecha_Inicio_Incapacidad` DATE NULL,
  `Fecha_Fin_Incapacidad` DATE NULL,
  `Dias` INT NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModI` VARCHAR(10) NULL,
  `Fecha_ModI` DATE NULL,
  PRIMARY KEY (`idIncapacidad`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Licencia` (
  `idLicencia` INT NOT NULL,
  `Fecha_InicioLicencia` DATE NULL,
  `Fecha_FinLicencia` DATE NULL,
  `ObservacionesLicencia` TEXT NULL,
  `IdPermiso` INT NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModL` VARCHAR(10) NULL,
  `Fecha_ModL` DATE NULL,
  PRIMARY KEY (`idLicencia`),
  INDEX `Permiso_idx` (`IdPermiso` ASC) VISIBLE,
  CONSTRAINT `Permiso`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `FH`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Movimiento` (
  `idMovimiento` INT NOT NULL,
  `Tipo` VARCHAR(15) NULL,
  `Departamento` VARCHAR(120) NULL,
  `Puesto` VARCHAR(75) NULL,
  `Fecha` DATE NULL,
  `Causa` TEXT NULL,
  `Observaciones` TEXT NULL,
  `Otros` TEXT NULL,
  `Depto_Actual` VARCHAR(150) NULL,
  `Puesto_Actual` VARCHAR(150) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModM` VARCHAR(10) NULL,
  `Fecha_ModM` DATE NULL,
  PRIMARY KEY (`idMovimiento`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Pension_Alimenticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Pension_Alimenticia` (
  `idPension_Alimenticia` INT NOT NULL,
  `Fecha_InicioPA` DATE NULL,
  `Fecha_FinPA` DATE NULL,
  `Nombre_HijoPA` VARCHAR(150) NULL,
  `Acta_Matrimonio` VARCHAR(15) NULL,
  `Acta_Hijo` VARCHAR(15) NULL,
  `Constancia_Estudios_Hijo` VARCHAR(30) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModPA` VARCHAR(10) NULL,
  `Fecha_ModPA` DATE NULL,
  PRIMARY KEY (`idPension_Alimenticia`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `Tipo_Permiso` VARCHAR(15) NULL,
  `Fecha_InicioPermiso` DATE NULL,
  `Fecha_FinPermiso` DATE NULL,
  `Observaciones` TEXT NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModPms` VARCHAR(10) NULL,
  `Fecha_ModPms` DATE NULL,
  PRIMARY KEY (`idPermisos`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Personales` (
  `PersonalesID` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Tipo_Sangre` VARCHAR(5) NULL,
  `Discapacidad` BINARY(1) NULL,
  `Tipo_Discapacidad` VARCHAR(45) NULL,
  `Madre` VARCHAR(150) NULL,
  `Padre` VARCHAR(150) NULL,
  `Licencia_Conducir` VARCHAR(15) NULL,
  `Licencia_vigencia` DATE NULL,
  `Licencia_Lugar_Expedicion` VARCHAR(25) NULL,
  `Pension_Alimenticia` BINARY(1) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModPsns` VARCHAR(10) NULL,
  `Fecha_ModPsns` DATE NULL,
  PRIMARY KEY (`PersonalesID`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Placa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Placa` (
  `idPlaca` INT NOT NULL,
  `No_Placa` VARCHAR(30) NULL,
  `CUIP` VARCHAR(30) NULL,
  `No_CUIP` VARCHAR(30) NULL,
  `Situacion_CUIP` VARCHAR(30) NULL,
  `Fecha_Em_CUP` DATE NULL,
  `CUP` BINARY NULL,
  `No_CUP` VARCHAR(30) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModPlc` VARCHAR(10) NULL,
  `Fecha_ModPlc` DATE NULL,
  PRIMARY KEY (`idPlaca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Salario` (
  `idSalario` INT NOT NULL,
  `Bruto` DECIMAL(8,2) NULL,
  `Neto` DECIMAL(8,2) NULL,
  `Canasta_Basica` DECIMAL(8,2) NULL,
  `Cup_Bruto` DECIMAL(8,2) NULL,
  `Cup_Neto` DECIMAL(8,2) NULL,
  `Total_Bruto` DECIMAL(8,2) NULL,
  `Total_Neto(8,2)` DECIMAL(8,2) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModSlr` VARCHAR(10) NULL,
  `Fecha_ModSlr` DATE NULL,
  PRIMARY KEY (`idSalario`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Sanciones` (
  `idSanciones` INT NOT NULL,
  `Tipo_Sancion` VARCHAR(75) NULL,
  `Folio_Oficio_Sancion` VARCHAR(30) NULL,
  `Fecha_Efecto` DATE NULL,
  `Fecha_Reincorporacion` DATE NULL,
  `Asunto` TEXT NULL,
  `Tipo` VARCHAR(10) NULL,
  `CURP` VARCHAR(20) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModScs` VARCHAR(10) NULL,
  `Fecha_ModScs` DATE NULL,
  PRIMARY KEY (`idSanciones`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `PaternoU` VARCHAR(20) NULL,
  `MaternoU` VARCHAR(20) NULL,
  `No_ControlU` VARCHAR(10) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Area` VARCHAR(15) NULL,
  `Tipo_Cuenta` VARCHAR(15) NULL,
  `Contraseña` VARCHAR(10) NULL,
  `Estatus` BINARY NULL,
  `Fecha_Registro` DATE NULL,
  `Fecha_Actualizacion` DATE NULL,
  `Estatus_ModU` VARCHAR(10) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Vacaciones` (
  `idVacaciones` INT NOT NULL,
  `Fecha_InicioVacaciones` DATE NULL,
  `Fecha_FinVacaciones` DATE NULL,
  `Tipo` TEXT NULL,
  `IdPermiso` INT NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModV` VARCHAR(10) NULL,
  `Fecha_ModV` DATE NULL,
  `Vacacionescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVacaciones`),
  INDEX `Permiso_idx` (`IdPermiso` ASC) VISIBLE,
  CONSTRAINT `Permiso`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `FH`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Seguro_Vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Seguro_Vida` (
  `idSeguro_Vida` INT NOT NULL,
  `CURP` VARCHAR(20) NULL,
  `Poliza` VARCHAR(13) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModSV` VARCHAR(10) NULL,
  `Fecha_ModSV` DATE NULL,
  PRIMARY KEY (`idSeguro_Vida`),
  INDEX `CURP_idx` (`CURP` ASC) VISIBLE,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `FH`.`` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HST`.`Beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HST`.`Beneficiarios` (
  `idBeneficiarios` INT NOT NULL,
  `Nombre_Beneficiario` VARCHAR(150) NULL,
  `Parentesco` VARCHAR(20) NULL,
  `Porcentaje` INT(11) NULL,
  `idSeguro_Vida` INT NULL,
  `Usuario` VARCHAR(10) NULL,
  `Estatus_ModBe` VARCHAR(10) NULL,
  `Fecha_ModBe` DATE NULL,
  PRIMARY KEY (`idBeneficiarios`),
  INDEX `IdSeguro_Vida_idx` (`idSeguro_Vida` ASC) VISIBLE,
  CONSTRAINT `IdSeguro_Vida`
    FOREIGN KEY (`idSeguro_Vida`)
    REFERENCES `FH`.`Seguro_Vida` (`idSeguro_Vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
